#pragma once
#include <acpi.h>
#include <common.h>

// Fixed ACPI Description Table (aka FADT)

/* Table signature */
#define ACPI_FACP_SIGNATURE 'F', 'A', 'C', 'P'
#define ACPI_FACP_REVISION 6
// #define ACPI_FACP_REVISION 5

#define ACPI_FACP_TABLE_STRUCTURE_NAME FIXED_ACPI_DESCRIPTION_TABLE

/* Body Structures */
// FACP data structures are fixed
typedef struct {
  // Add any extra fields if needed in future revisions
  UINT32 FIRMWARE_CTRL;
  UINT32 DSDT;
  UINT8 Reserved;
  UINT8 Preferred_PM_Profile;
  UINT16 SCI_INT;
  UINT32 SMI_CMD;
  UINT8 ACPI_ENABLE;
  UINT8 ACPI_DISABLE;
  UINT8 S4BIOS_REQ;
  UINT8 PSTATE_CNT;
  UINT32 PM1a_EVT_BLK;
  UINT32 PM1b_EVT_BLK;
  UINT32 PM1a_CNT_BLK;
  UINT32 PM1b_CNT_BLK;
  UINT32 PM2_CNT_BLK;
  UINT32 PM_TMR_BLK;
  UINT32 GPE0_BLK;
  UINT32 GPE1_BLK;
  UINT8 PM1_EVT_LEN;
  UINT8 PM1_CNT_LEN;
  UINT8 PM2_CNT_LEN;
  UINT8 PM_TMR_LEN;
  UINT8 GPE0_BLK_LEN;
  UINT8 GPE1_BLK_LEN;
  UINT8 GPE1_BASE;
  UINT8 CST_CNT;
  UINT16 P_LVL2_LAT;
  UINT16 P_LVL3_LAT;
  UINT16 FLUSH_SIZE;
  UINT16 FLUSH_STRIDE;
  UINT8 DUTY_OFFSET;
  UINT8 DUTY_WIDTH;
  UINT8 DAY_ALRM;
  UINT8 MON_ALRM;
  UINT8 CENTURY;
  UINT16 IAPC_BOOT_ARCH;
  UINT8 Reserved2;
  UINT32 Flags;
  ACPI_GENERIC_ADDRESS_STRUCTURE ResetReg;
  UINT8 ResetValue;
  UINT16 ARM_BOOT_ARCH;
  UINT8 MinorRevision;
  UINT64 X_FIRMWARE_CTRL;
  UINT64 X_DSDT;
  ACPI_GENERIC_ADDRESS_STRUCTURE X_PM1a_EVT_BLK;
  ACPI_GENERIC_ADDRESS_STRUCTURE X_PM1b_EVT_BLK;
  ACPI_GENERIC_ADDRESS_STRUCTURE X_PM1a_CNT_BLK;
  ACPI_GENERIC_ADDRESS_STRUCTURE X_PM1b_CNT_BLK;
  ACPI_GENERIC_ADDRESS_STRUCTURE X_PM2_CNT_BLK;
  ACPI_GENERIC_ADDRESS_STRUCTURE X_PM_TMR_BLK;
  ACPI_GENERIC_ADDRESS_STRUCTURE X_GPE0_BLK;
  ACPI_GENERIC_ADDRESS_STRUCTURE X_GPE1_BLK;
  ACPI_GENERIC_ADDRESS_STRUCTURE SLEEP_CONTROL_REG;
  ACPI_GENERIC_ADDRESS_STRUCTURE SLEEP_STATUS_REG;
  UINT64 HypervisorVendorIdentity;
} __attribute__((packed)) FACP_DATA_STRUCTURE;
_Static_assert(sizeof(FACP_DATA_STRUCTURE) == 240,
               "FACP_DATA_STRUCTURE size is incorrect");

enum FACP_ARM_BOOT_ARCH {
  FACP_ARM_BOOT_ARCH_PSCI_COMPLIANCE = BIT(0),
  FACP_ARM_BOOT_ARCH_PSCI_USE_HVC = BIT(1),
  FACP_ARM_BOOT_ARCH_RESERVED = GEN_MSK(15, 2)
};

// FACP Flags
#define FACP_FLAG_WBINVD BIT(0)
#define FACP_FLAG_WBINVD_FLUSH BIT(1)
#define FACP_FLAG_PROC_C1 BIT(2)
#define FACP_FLAG_P_LVL2_UP BIT(3)
#define FACP_FLAG_PWR_BUTTON BIT(4)
#define FACP_FLAG_SLP_BUTTON BIT(5)
#define FACP_FLAG_FIX_RTC BIT(6)
#define FACP_FLAG_RTC_S4 BIT(7)
#define FACP_FLAG_TMR_VAL_EXT BIT(8)
#define FACP_FLAG_DCK_CAP BIT(9)
#define FACP_FLAG_RESET_REG_SUP BIT(10)
#define FACP_FLAG_SEALED_CASE BIT(11)
#define FACP_FLAG_HEADLESS BIT(12)
#define FACP_FLAG_CPU_SW_SLP BIT(13)
#define FACP_FLAG_PCI_EXP_WAK BIT(14)
#define FACP_FLAG_USE_PLATFORM_CLOCK BIT(15)
#define FACP_FLAG_S4_RTC_STS_VALID BIT(16)
#define FACP_FLAG_REMOTE_POWER_ON_CAPABLE BIT(17)
#define FACP_FLAG_FORCE_APIC_CLUSTER_MODEL BIT(18)
#define FACP_FLAG_FORCE_APIC_PHYSICAL_DESTINATION_MODE BIT(19)
#define FACP_FLAG_HW_REDUCED_ACPI BIT(20)
#define FACP_FLAG_LOW_POWER_S0_IDLE_CAPABLE BIT(21)
#define FACP_FLAG_PRESISTENT_CPU_CACHES GEN_MSK()(23, 22)
#define FACP_FLAG_RESERVED GEN_MSK(31, 24)

// Preferred PM profile values
enum FACP_PM_PROFILE {
  FACP_PM_PROFILE_UNSPECIFIED = 0,
  FACP_PM_PROFILE_DESKTOP = 1,
  FACP_PM_PROFILE_MOBILE = 2,
  FACP_PM_PROFILE_WORKSTATION = 3,
  FACP_PM_PROFILE_ENTERPRISE_SERVER = 4,
  FACP_PM_PROFILE_SOHO_SERVER = 5,
  FACP_PM_PROFILE_APPLIANCE_PC = 6,
  FACP_PM_PROFILE_PERFORMANCE_SERVER = 7,
  FACP_PM_PROFILE_TABLET = 8,
  FACP_PM_PROFILE_RESERVED = 0xFF
};

/* Helper macros */
#define FACP_DEFINE_TABLE                                                      \
  typedef struct {                                                             \
    ACPI_TABLE_HEADER Header;                                                  \
    FACP_DATA_STRUCTURE FacpDataStructure;                                     \
  } __attribute__((packed)) ACPI_FACP_TABLE_STRUCTURE_NAME;

#define FACP_DECLARE_HEADER                                                    \
  ACPI_DECLARE_TABLE_HEADER(                                                   \
      ACPI_FACP_SIGNATURE, ACPI_FACP_TABLE_STRUCTURE_NAME, ACPI_FACP_REVISION)

/* FACP Table with Magic */
#define FACP_DEFINE_WITH_MAGIC                                                 \
  ACPI_TABLE_WITH_MAGIC(ACPI_FACP_TABLE_STRUCTURE_NAME)
#define FACP_START ACPI_TABLE_START(ACPI_FACP_TABLE_STRUCTURE_NAME)
#define FACP_END ACPI_TABLE_END(ACPI_FACP_TABLE_STRUCTURE_NAME)